echo -fno-defer-pop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-defer-pop; }
echo -fforward-propagate && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fforward-propagate; }
echo -ffp-contract=style && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffp-contract=style; }
echo -fomit-frame-pointer && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fomit-frame-pointer; }
echo -foptimize-sibling-calls && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -foptimize-sibling-calls; }
echo -foptimize-strlen && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -foptimize-strlen; }
echo -fno-inline && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-inline; }
echo -finline-small-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -finline-small-functions; }
echo -findirect-inlining && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -findirect-inlining; }
echo -finline-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -finline-functions; }
echo -finline-functions-called-once && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -finline-functions-called-once; }
echo -fearly-inlining && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fearly-inlining; }
echo -fipa-sra && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-sra; }
echo -finline-limit=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -finline-limit=n; }
echo -fno-keep-inline-dllexport && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-keep-inline-dllexport; }
echo -fkeep-inline-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fkeep-inline-functions; }
echo -fkeep-static-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fkeep-static-functions; }
echo -fkeep-static-consts && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fkeep-static-consts; }
echo -fmerge-constants && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmerge-constants; }
echo -fmerge-all-constants && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmerge-all-constants; }
echo -fmodulo-sched && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmodulo-sched; }
echo -fmodulo-sched-allow-regmoves && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmodulo-sched-allow-regmoves; }
echo -fno-branch-count-reg && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-branch-count-reg; }
echo -fno-function-cse && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-function-cse; }
echo -fno-zero-initialized-in-bss && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-zero-initialized-in-bss; }
echo -fthread-jumps && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fthread-jumps; }
echo -fsplit-wide-types && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsplit-wide-types; }
echo -fsplit-wide-types-early && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsplit-wide-types-early; }
echo -fcse-follow-jumps && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcse-follow-jumps; }
echo -fcse-skip-blocks && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcse-skip-blocks; }
echo -frerun-cse-after-loop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -frerun-cse-after-loop; }
echo -fgcse && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgcse; }
echo -fgcse-lm && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgcse-lm; }
echo -fgcse-sm && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgcse-sm; }
echo -fgcse-las && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgcse-las; }
echo -fgcse-after-reload && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgcse-after-reload; }
echo -faggressive-loop-optimizations && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -faggressive-loop-optimizations; }
echo -funconstrained-commons && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funconstrained-commons; }
echo -fcrossjumping && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcrossjumping; }
echo -fauto-inc-dec && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fauto-inc-dec; }
echo -fdce && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdce; }
echo -fdse && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdse; }
echo -fif-conversion && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fif-conversion; }
echo -fif-conversion2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fif-conversion2; }
echo -fdeclone-ctor-dtor && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdeclone-ctor-dtor; }
echo -fdelete-null-pointer-checks && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdelete-null-pointer-checks; }
echo -fdevirtualize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdevirtualize; }
echo -fdevirtualize-speculatively && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdevirtualize-speculatively; }
echo -fdevirtualize-at-ltrans && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdevirtualize-at-ltrans; }
echo -fexpensive-optimizations && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fexpensive-optimizations; }
echo -free && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -free; }
echo -fno-lifetime-dse && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-lifetime-dse; }
echo -flive-range-shrinkage && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flive-range-shrinkage; }
echo -fira-algorithm=algorithm && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fira-algorithm=algorithm; }
echo -fira-region=region && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fira-region=region; }
echo -fira-hoist-pressure && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fira-hoist-pressure; }
echo -fira-loop-pressure && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fira-loop-pressure; }
echo -fno-ira-share-save-slots && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-ira-share-save-slots; }
echo -fno-ira-share-spill-slots && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-ira-share-spill-slots; }
echo -flra-remat && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flra-remat; }
echo -fdelayed-branch && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdelayed-branch; }
echo -fschedule-insns && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fschedule-insns; }
echo -fschedule-insns2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fschedule-insns2; }
echo -fno-sched-interblock && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-sched-interblock; }
echo -fno-sched-spec && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-sched-spec; }
echo -fsched-pressure && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-pressure; }
echo -fsched-spec-load && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-spec-load; }
echo -fsched-spec-load-dangerous && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-spec-load-dangerous; }
echo -fsched-stalled-insns && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-stalled-insns; }
echo -fsched-stalled-insns=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-stalled-insns=n; }
echo -fsched-stalled-insns-dep && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-stalled-insns-dep; }
echo -fsched-stalled-insns-dep=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-stalled-insns-dep=n; }
echo -fsched2-use-superblocks && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched2-use-superblocks; }
echo -fsched-group-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-group-heuristic; }
echo -fsched-critical-path-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-critical-path-heuristic; }
echo -fsched-spec-insn-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-spec-insn-heuristic; }
echo -fsched-rank-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-rank-heuristic; }
echo -fsched-last-insn-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-last-insn-heuristic; }
echo -fsched-dep-count-heuristic && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsched-dep-count-heuristic; }
echo -freschedule-modulo-scheduled-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freschedule-modulo-scheduled-loops; }
echo -fselective-scheduling && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fselective-scheduling; }
echo -fselective-scheduling2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fselective-scheduling2; }
echo -fsel-sched-pipelining && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsel-sched-pipelining; }
echo -fsel-sched-pipelining-outer-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsel-sched-pipelining-outer-loops; }
echo -fsemantic-interposition && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsemantic-interposition; }
echo -fshrink-wrap && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fshrink-wrap; }
echo -fshrink-wrap-separate && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fshrink-wrap-separate; }
echo -fcaller-saves && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcaller-saves; }
echo -fcombine-stack-adjustments && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcombine-stack-adjustments; }
echo -fipa-ra && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-ra; }
echo -fconserve-stack && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fconserve-stack; }
echo -ftree-reassoc && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-reassoc; }
echo -fcode-hoisting && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcode-hoisting; }
echo -ftree-pre && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-pre; }
echo -ftree-partial-pre && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-partial-pre; }
echo -ftree-forwprop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-forwprop; }
echo -ftree-fre && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-fre; }
echo -ftree-phiprop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-phiprop; }
echo -fhoist-adjacent-loads && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fhoist-adjacent-loads; }
echo -ftree-copy-prop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-copy-prop; }
echo -fipa-pure-const && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-pure-const; }
echo -fipa-reference && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-reference; }
echo -fipa-reference-addressable && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-reference-addressable; }
echo -fipa-stack-alignment && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-stack-alignment; }
echo -fipa-pta && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-pta; }
echo -fipa-profile && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-profile; }
echo -fipa-modref && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-modref; }
echo -fipa-cp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-cp; }
echo -fipa-cp-clone && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-cp-clone; }
echo -fipa-bit-cp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-bit-cp; }
echo -fipa-vrp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-vrp; }
echo -fipa-icf && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-icf; }
echo -flive-patching=level && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flive-patching=level; }
echo -fisolate-erroneous-paths-dereference && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fisolate-erroneous-paths-dereference; }
echo -fisolate-erroneous-paths-attribute && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fisolate-erroneous-paths-attribute; }
echo -ftree-sink && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-sink; }
echo -ftree-bit-ccp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-bit-ccp; }
echo -ftree-ccp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-ccp; }
echo -fssa-backprop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fssa-backprop; }
echo -fssa-phiopt && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fssa-phiopt; }
echo -ftree-switch-conversion && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-switch-conversion; }
echo -ftree-tail-merge && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-tail-merge; }
echo -ftree-dce && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-dce; }
echo -ftree-builtin-call-dce && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-builtin-call-dce; }
echo -ffinite-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffinite-loops; }
echo -ftree-dominator-opts && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-dominator-opts; }
echo -ftree-dse && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-dse; }
echo -ftree-ch && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-ch; }
echo -ftree-loop-optimize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-optimize; }
echo -ftree-loop-linear && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-linear; }
echo -floop-strip-mine && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-strip-mine; }
echo -floop-block && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-block; }
echo -fgraphite-identity && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fgraphite-identity; }
echo -floop-nest-optimize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-nest-optimize; }
echo -floop-parallelize-all && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-parallelize-all; }
echo -ftree-coalesce-vars && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-coalesce-vars; }
echo -ftree-loop-if-convert && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-if-convert; }
echo -ftree-loop-distribution && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-distribution; }
echo -ftree-loop-distribute-patterns && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-distribute-patterns; }
echo -floop-interchange && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-interchange; }
echo -floop-unroll-and-jam && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -floop-unroll-and-jam; }
echo -ftree-loop-im && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-im; }
echo -ftree-loop-ivcanon && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-ivcanon; }
echo -ftree-scev-cprop && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-scev-cprop; }
echo -fivopts && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fivopts; }
echo -ftree-parallelize-loops=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-parallelize-loops=n; }
echo -ftree-pta && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-pta; }
echo -ftree-sra && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-sra; }
echo -fstore-merging && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fstore-merging; }
echo -ftree-ter && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-ter; }
echo -ftree-slsr && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-slsr; }
echo -ftree-vectorize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-vectorize; }
echo -ftree-loop-vectorize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-loop-vectorize; }
echo -ftree-slp-vectorize && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-slp-vectorize; }
echo -ftrivial-auto-var-init=choice && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftrivial-auto-var-init=choice; }
echo -fvect-cost-model=model && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fvect-cost-model=model; }
echo -fsimd-cost-model=model && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsimd-cost-model=model; }
echo -ftree-vrp && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftree-vrp; }
echo -fsplit-paths && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsplit-paths; }
echo -fsplit-ivs-in-unroller && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsplit-ivs-in-unroller; }
echo -fvariable-expansion-in-unroller && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fvariable-expansion-in-unroller; }
echo -fpartial-inlining && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fpartial-inlining; }
echo -fpredictive-commoning && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fpredictive-commoning; }
echo -fprefetch-loop-arrays && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprefetch-loop-arrays; }
echo -fno-printf-return-value && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-printf-return-value; }
echo -fno-peephole && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-peephole; }
echo -fno-peephole2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-peephole2; }
echo -fno-guess-branch-probability && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-guess-branch-probability; }
echo -freorder-blocks && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freorder-blocks; }
echo -freorder-blocks-algorithm=algorithm && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freorder-blocks-algorithm=algorithm; }
echo -freorder-blocks-and-partition && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freorder-blocks-and-partition; }
echo -freorder-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freorder-functions; }
echo -fstrict-aliasing && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fstrict-aliasing; }
echo -fipa-strict-aliasing && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fipa-strict-aliasing; }
echo -falign-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-functions; }
echo -falign-functions=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-functions=n; }
echo -falign-functions=n:m && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-functions=n:m; }
echo -falign-functions=n:m:n2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-functions=n:m:n2; }
echo -falign-functions=n:m:n2:m2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-functions=n:m:n2:m2; }
echo -flimit-function-alignment && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flimit-function-alignment; }
echo -falign-labels && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-labels; }
echo -falign-labels=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-labels=n; }
echo -falign-labels=n:m && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-labels=n:m; }
echo -falign-labels=n:m:n2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-labels=n:m:n2; }
echo -falign-labels=n:m:n2:m2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-labels=n:m:n2:m2; }
echo -falign-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-loops; }
echo -falign-loops=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-loops=n; }
echo -falign-loops=n:m && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-loops=n:m; }
echo -falign-loops=n:m:n2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-loops=n:m:n2; }
echo -falign-loops=n:m:n2:m2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-loops=n:m:n2:m2; }
echo -falign-jumps && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-jumps; }
echo -falign-jumps=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-jumps=n; }
echo -falign-jumps=n:m && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-jumps=n:m; }
echo -falign-jumps=n:m:n2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-jumps=n:m:n2; }
echo -falign-jumps=n:m:n2:m2 && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -falign-jumps=n:m:n2:m2; }
echo -fno-allocation-dce && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-allocation-dce; }
echo -fallow-store-data-races && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fallow-store-data-races; }
echo -funit-at-a-time && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funit-at-a-time; }
echo -fno-toplevel-reorder && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-toplevel-reorder; }
echo -fweb && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fweb; }
echo -fwhole-program && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fwhole-program; }
echo -flto[=n] && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flto[=n]; }
echo -flto-partition=alg && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flto-partition=alg; }
echo -flto-compression-level=n && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -flto-compression-level=n; }
echo -fuse-linker-plugin && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fuse-linker-plugin; }
echo -ffat-lto-objects && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffat-lto-objects; }
echo -fcompare-elim && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcompare-elim; }
echo -fcprop-registers && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcprop-registers; }
echo -fprofile-correction && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-correction; }
echo -fprofile-partial-training && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-partial-training; }
echo -fprofile-use && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-use; }
echo -fprofile-partial-training && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-partial-training; }
echo -fprofile-use && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-use; }
echo -fprofile-use=path && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-use=path; }
echo -fauto-profile && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fauto-profile; }
echo -fauto-profile=path && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fauto-profile=path; }
echo -ffloat-store && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffloat-store; }
echo -fexcess-precision=style && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fexcess-precision=style; }
echo -ffast-math && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffast-math; }
echo -fno-math-errno && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-math-errno; }
echo -funsafe-math-optimizations && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funsafe-math-optimizations; }
echo -fassociative-math && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fassociative-math; }
echo -freciprocal-math && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -freciprocal-math; }
echo -ffinite-math-only && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffinite-math-only; }
echo -fno-signed-zeros && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-signed-zeros; }
echo -fno-trapping-math && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-trapping-math; }
echo -frounding-math && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -frounding-math; }
echo -fsignaling-nans && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsignaling-nans; }
echo -fno-fp-int-builtin-inexact && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fno-fp-int-builtin-inexact; }
echo -fsingle-precision-constant && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsingle-precision-constant; }
echo -fcx-limited-range && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcx-limited-range; }
echo -fcx-fortran-rules && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fcx-fortran-rules; }
echo -fbranch-probabilities && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fbranch-probabilities; }
echo -fprofile-values && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-values; }
echo -fprofile-reorder-functions && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fprofile-reorder-functions; }
echo -fvpt && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fvpt; }
echo -frename-registers && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -frename-registers; }
echo -fschedule-fusion && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fschedule-fusion; }
echo -ftracer && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ftracer; }
echo -funroll-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funroll-loops; }
echo -funroll-all-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funroll-all-loops; }
echo -fpeel-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fpeel-loops; }
echo -fmove-loop-invariants && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmove-loop-invariants; }
echo -fmove-loop-stores && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fmove-loop-stores; }
echo -fsplit-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsplit-loops; }
echo -funswitch-loops && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -funswitch-loops; }
echo -fversion-loops-for-strides && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fversion-loops-for-strides; }
echo -ffunction-sections && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -ffunction-sections; }
echo -fdata-sections && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fdata-sections; }
echo -fstdarg-opt && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fstdarg-opt; }
echo -fsection-anchors && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fsection-anchors; }
echo -fzero-call-used-regs=choice && { time /usr/local/Cellar/gcc/11.2.0_3/bin/g++-11 -D GLIBCXX_DEBUG -Wl,-demangle -std=c++17 -Wall -Werror -fsanitize=undefined -g ac.cpp -fzero-call-used-regs=choice; }
