#!/usr/bin/env python3.8
import sys

MOD = 998244353  # type: int


def solve(K: int, N: int, x: "List[int]"):
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    N = int(next(tokens))  # type: int
    x = [int(next(tokens)) for _ in range(K)]  # type: "List[int]"
    solve(K, N, x)

if __name__ == '__main__':
    main()
