#!/usr/bin/env python3.8
import sys


def solve(X: str, M: int):
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = next(tokens)  # type: str
    M = int(next(tokens))  # type: int
    solve(X, M)

if __name__ == '__main__':
    main()
