#!/usr/bin/env python3.8
import sys


def solve(N: int, M: int, Q: int, u: "List[int]", v: "List[int]", x: "List[int]"):
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    Q = int(next(tokens))  # type: int
    u = [int()] * (M)  # type: "List[int]"
    v = [int()] * (M)  # type: "List[int]"
    for i in range(M):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
    x = [int(next(tokens)) for _ in range(Q)]  # type: "List[int]"
    solve(N, M, Q, u, v, x)

if __name__ == '__main__':
    main()
