#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;


void solve(long long N, long long A, std::vector<std::string> op, std::vector<long long> B){

}

// Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    std::scanf("%lld", &N);
    long long A;
    std::scanf("%lld", &A);
    std::vector<std::string> op(N);
    std::vector<long long> B(N);
    for(int i = 0 ; i < N ; i++){
        std::cin >> op[i];
        std::scanf("%lld", &B[i]);
    }
    solve(N, A, std::move(op), std::move(B));
    return 0;
}
