#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, T: int, AX: "List[int]", AY: "List[int]", BX: "List[int]", BY: "List[int]"):
    return


# Generated by 2.6.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    AX = [int()] * (N)  # type: "List[int]"
    AY = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        AX[i] = int(next(tokens))
        AY[i] = int(next(tokens))
    BX = [int()] * (N)  # type: "List[int]"
    BY = [int()] * (N)  # type: "List[int]"
    for i in range(N):
        BX[i] = int(next(tokens))
        BY[i] = int(next(tokens))
    solve(N, T, AX, AY, BX, BY)

if __name__ == '__main__':
    main()
